ALTER TABLE settings ADD COLUMN IF NOT EXISTS services JSONB DEFAULT '[]'::jsonb;
ALTER TABLE settings ADD COLUMN IF NOT EXISTS pix_key TEXT;
ALTER TABLE settings ADD COLUMN IF NOT EXISTS pix_name TEXT;
ALTER TABLE settings ADD COLUMN IF NOT EXISTS city TEXT;
ALTER TABLE settings ADD COLUMN IF NOT EXISTS infinite_pay_tag TEXT;
ALTER TABLE settings ADD COLUMN IF NOT EXISTS activity_log BOOLEAN DEFAULT false;
ALTER TABLE settings ADD COLUMN IF NOT EXISTS two_factor BOOLEAN DEFAULT false;
